export * from './CarrouselMain'
export * from './NavMain'
export * from './InfoGeneral'
export * from './Noticias'
export * from './InputBusqueda/InputBusqueda'
export * from './Banners'
export * from './Footers'